#!/bin/sh
exec 2>&1

. /mnt/cert-issuer/certificate-issuer.env

exec chpst -uroot /usr/bin/certificate-issuer \
    --api-addr                  "127.0.0.1:3000"                                   \
    --cloudflare-api-key-path   "${CLOUDFLARE_API_KEY_PATH}"                       \
    --delegation-domain         "${DELEGATION_DOMAIN}"                             \
    --identity-path             "${IDENTITY_PATH}"                                 \
    --key-path                  "${KEY_PATH}"                                      \
    --metrics-addr              "[::]:9321"                                        \
    --orchestrator-canister-id  "${ORCHESTRATOR_CANISTER_ID}"                      \
    --orchestrator-uri          "${ORCHESTRATOR_URI}"                              \
    --root-key-path             "${NNS_KEY_PATH}"                                  \
    ${ACME_ACCOUNT_ID:+        --acme-account-id       "${ACME_ACCOUNT_ID}"}       \
    ${ACME_ACCOUNT_KEY_PATH:+  --acme-account-key-path "${ACME_ACCOUNT_KEY_PATH}"} \
    ${ACME_PROVIDER_URL:+      --acme-provider-url     "${ACME_PROVIDER_URL}"}     \
    ${CLOUDFLARE_API_URL:+     --cloudflare-api-url    "${CLOUDFLARE_API_URL}"}    \
    ${IMPORTANT_DOMAINS:+      --important-domains     "${IMPORTANT_DOMAINS}"}     \
    ${NAME_SERVERS_PORT:+      --name-servers-port     "${NAME_SERVERS_PORT}"}     \
    ${NAME_SERVERS:+           --name-servers          "${NAME_SERVERS}"}          \
    ${PEEK_SLEEP_SEC:+         --peek-sleep-sec        "${PEEK_SLEEP_SEC}"}        \
    ${TASK_DELAY_SEC:+         --task-delay-sec        "${TASK_DELAY_SEC}"}        \
    ${TASK_ERROR_DELAY_SEC:+   --task-error-delay-sec  "${TASK_ERROR_DELAY_SEC}"}
