#!/bin/sh

if [ ! -d /mnt/ic-gateway ]; then
    sleep 86400
    exit
fi

LOG_DIR='/var/log/ic-gateway'

# Create log dir
if [ ! -d $LOG_DIR ]; then
    mkdir -p $LOG_DIR
fi

exec chpst -uroot svlogd -tt $LOG_DIR
