name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - refs.json

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Create initramfs
        run: make initramfs
        env:
          GH_TOKEN: ${{ secrets.IC_HTTP_LB_RELEASE_GH_TOKEN }}

      - name: Take SEV-SNP measurement
        run: echo "SEV_SNP_MEASUREMENT=$(make sev-snp-measure)" >> $GITHUB_ENV

      - name: Set short sha
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c -7)" >> $GITHUB_ENV

      - name: Calculate artifact checksums
        run: |
          echo "INITRAMFS_SHASUM=$(sha256sum initramfs.cpio.gz | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "VMLINUZ_SHASUM=$(sha256sum deps/vmlinuz | cut -d' ' -f1)" >> $GITHUB_ENV
          echo "OVMF_SHASUM=$(sha256sum deps/OVMF.fd | cut -d' ' -f1)" >> $GITHUB_ENV
        shell: bash

      - name: release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8
        with:
          tag_name: ${{ env.SHORT_SHA }}
          files: |
            deps/OVMF.fd
            deps/vmlinuz
            initramfs.cpio.gz
          body: |
            | Name | Value |
            | ------------- | ------------- |
            | Local | [${{ github.repository }}:${{ github.sha }}](https://github.com/${{ github.repository }}/tree/${{ github.sha }}) |
            | SEV_SNP_MEASUREMENT | `${{ env.SEV_SNP_MEASUREMENT }}` |

            ### Artifact Hashes
            | Artifact | Checksum |
            | ------------- | ------------- |
            | initramfs.cpio.gz | `${{ env.INITRAMFS_SHASUM }}` |
            | OVMF.fd | `${{ env.OVMF_SHASUM }}` |
            | vmlinuz | `${{ env.VMLINUZ_SHASUM }}` |
